[workspace]
members = ["packages/*", "contracts/*"]

resolver = "2"

[workspace.package]
version = "2.0.0"

[workspace.dependencies]
cosmwasm-schema = "1.5.3"
cosmwasm-std = "1.5.3"
cw-storage-plus = "1.2.0"
schemars = "0.8.15"
cw2 = "1.1.2"
hex = "0.4.3"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.57" }
tiny-keccak = { version = "2.0", features = ["keccak"] }
babylon-bindings = {git = "https://github.com/babylonchain/bindings", tag = "v0.1.0"}

avs-directory = { path = "contracts/avs-directory", version = "0.2.0", features = ["library"] }
delegation-manager = { path = "contracts/delegation-manager", version = "0.2.0", features = ["library"] }
rewards-coordinator = { path = "contracts/rewards-coordinator", version = "0.2.0", features = ["library"] }
slash-manager = { path = "contracts/slash-manager", version = "0.2.0", features = ["library"] }
strategy-manager = { path = "contracts/strategy-manager", version = "0.2.0", features = ["library"] }
cw20 = { path = "packages/cw20", version = "2.0.0-rc.0" }


[profile.release.package.cw1-subkeys]
codegen-units = 1
incremental = false

[profile.release.package.cw1-whitelist]
codegen-units = 1
incremental = false

[profile.release.package.cw3-fixed-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw3-flex-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw4-group]
codegen-units = 1
incremental = false

[profile.release.package.cw4-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw20-base]
codegen-units = 1
incremental = false

[profile.release.package.cw20-ics20]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
